export const COMMON_IC = {
  access_alarm: require('@icons/access_alarm.png'),
  add_alarm: require('@icons/add_alarm.png'),
  arrow_back: require('@icons/arrow_back.png'),
  arrow_down: require('@icons/arrow_down.png'),
  check_off: require('@icons/check_off.png'),
  check_on: require('@icons/check_on.png'),
  refresh: require('@icons/refresh.png'),
  sort: require('@icons/sort.png'),
  time_table: require('@icons/time_table.png'),
  toggle_off: require('@icons/toggle_off.png'),
  toggle_on: require('@icons/toggle_on.png'),
  drop_down: require('@icons/drop_down.png'),
  trash: require('@icons/trash.png'),
};
